name: Agente de Analise de Mercado


on:

  schedule:

    # Executa a cada 5 minutos

    - cron: "*/5 * * * *"


  workflow_dispatch:



jobs:


  executar-agente:


    runs-on: ubuntu-latest



    steps:


    # Baixar o código do repositório

    - name: Baixar codigo

      uses: actions/checkout@v4



    # Instalar Node.js

    - name: Configurar Node

      uses: actions/setup-node@v4

      with:

        node-version: 20



    # Instalar bibliotecas

    - name: Instalar dependencias

      run:

        npm install



    # Executar agente

    - name: Executar analise

      env:

        TWELVEDATA_KEY: ${{ secrets.TWELVEDATA_KEY }}

      run:

        node index.js
